
name: Maven Package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Install prerequisites
      run:
        sudo
        DEBIAN_FRONTEND=noninteractive
        apt-get -y --no-install-recommends install
          siege

    - uses: actions/checkout@v2

    - name: Checkout utils
      uses: actions/checkout@v2
      with:
        repository: CRaC/utils
        path: utils

    - run: make -C utils

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - run: mvn -B package

    - name: Test on Vanila JDK
      run: |
        P=$(utils/start-bg.sh \
          -s "Started Application" \
          java -jar target/spring-boot-0.0.1-SNAPSHOT.jar)
        curl localhost:8080 | grep "Greetings from Spring Boot!"
        utils/bench.sh http://localhost:8080
        kill $P

    - name: Download JDK
      run: |
        archive=$(utils/download-jdk.sh)
        sudo tar -axf $archive
        echo JDK=${archive%%.tar.gz} >> $GITHUB_ENV

    - name: Prepare warm checkpoint
      run: |
        P=$(utils/start-bg.sh \
        -s "Started Application" \
        -e exitcode \
          ${{ env.JDK }}/bin/java \
          -XX:CRaCCheckpointTo=cr \
          -XX:+UnlockDiagnosticVMOptions \
          -XX:+CRTraceStartupTime \
          -Djdk.crac.trace-startup-time=true \
          --add-opens java.base/java.lang=ALL-UNNAMED \
          -jar target/spring-boot-0.0.1-SNAPSHOT.jar)

        # warmup the service
        utils/bench.sh http://localhost:8080
        jcmd $P JDK.checkpoint
        [ 137 = $(utils/read-exitcode.sh exitcode) ]

    - name: Test on C/RaC
      run: |
        P=$(utils/start-bg.sh \
          -s "restore-finish" \
          ${{ env.JDK }}/bin/java -XX:CRaCRestoreFrom=cr)
        curl localhost:8080 | grep "Greetings from Spring Boot!"
        utils/bench.sh http://localhost:8080
        kill $P

    - name: Test C/RaC startup time
      run:
        timeout 3 bash -c "utils/lib/javatime ; ${{ env.JDK }}/bin/java -XX:CRaCRestoreFrom=cr"
        | utils/sel.awk -v from=prestart -v to=restore-finish
