
name: Maven Package

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - run: mvn -s settings.xml -B package
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}

    - name: Download JDK
      run: |
        id=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/org-crac/jdk/releases/tags/release-crac | jq '.assets[] | select(.name == "jdk.tar.gz").id')
        curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/org-crac/jdk/releases/assets/$id -LJOH 'Accept: application/octet-stream'
        sudo tar -axf jdk.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}

    #- run: |
        #( jdk/bin/java -Zcheckpoint:cr -jar target/spring-boot-0.0.1-SNAPSHOT.jar  || echo $? > exitcode) &
        #sleep 10 # allow service to start
        #curl localhost:8080 # "warmup" the service
        #jcmd target/spring-boot-0.0.1-SNAPSHOT.jar JDK.checkpoint
        #sleep 10 # allow checkpoint to settle
        #[ 137 = $(< exitcode) ]
    - run: timeout 30 jdk/bin/java -Zcheckpoint:cr -jar target/spring-boot-0.0.1-SNAPSHOT.jar || [ $? = 137 ]
    - run: timeout 10 jdk/bin/java -Zrestore:cr || [ $? = 124 ]

